In [1]:
import torch
from transformers import AutoModel, AutoTokenizer, BertTokenizer

In [2]:
torch.set_grad_enabled(False)

In [3]:
model = AutoModel.from_pretrained("bert-base-cased")
tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")

In [4]:
tokens = tokenizer.tokenize("This is an input example")
print("Tokens: {}".format(tokens))

Tokens: ['This', 'is', 'an', 'input', 'example']


In [5]:
tokens_ids = tokenizer.convert_tokens_to_ids(tokens)
print("Tokens id: {}".format(tokens_ids))

Tokens id: [1188, 1110, 1126, 7758, 1859]


In [6]:
tokens_ids = tokenizer.build_inputs_with_special_tokens(tokens_ids)

In [7]:
tokens_pt = torch.tensor([tokens_ids])
print("Tokens PyTorch: {}".format(tokens_pt))

Tokens PyTorch: tensor([[ 101, 1188, 1110, 1126, 7758, 1859,  102]])


In [8]:
outputs, pooled = model(tokens_pt)
print("Token wise output: {}, Pooled output: {}".format(outputs.shape, pooled.shape))

Token wise output: torch.Size([1, 7, 768]), Pooled output: torch.Size([1, 768])


In [9]:
tokens_pt2 = tokenizer("This is an input example", return_tensors = "pt")

for key, value in tokens_pt2.items():
    print("{}:\n\t{}".format(key, value))

outputs2, pooled2 = model(**tokens_pt2)
print("Difference with previous code: ({}, {})".format((outputs2 - outputs).sum(), (pooled2 - pooled).sum()))

input_ids:
	tensor([[ 101, 1188, 1110, 1126, 7758, 1859,  102]])
token_type_ids:
	tensor([[0, 0, 0, 0, 0, 0, 0]])
attention_mask:
	tensor([[1, 1, 1, 1, 1, 1, 1]])
Difference with previous code: (0.0, 0.0)
